name: Publish to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'      
          
      - name: Generate settings.xml
        run: |
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"" > settings.xml
          echo "  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"" >> settings.xml
          echo "  xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\">" >> settings.xml
          echo "  <servers>" >> settings.xml
          echo "    <server>" >> settings.xml
          echo "      <id>github</id>" >> settings.xml
          echo "      <username>DingMa649108</username>" >> settings.xml
          echo "      <password>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</password>" >> settings.xml
          echo "    </server>" >> settings.xml
          echo "  </servers>" >> settings.xml
          echo "</settings>" >> settings.xml
          
      - name: Upload settings.xml artifact
        uses: actions/upload-artifact@v2
        with:
          name: settings-xml
          path: ./settings.xml

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: 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
          
     
